apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: mqtt
  namespace: mosquitto
spec:
  entryPoints: [int-mqtt]
  routes:
    - match: HostSNI(`*`)
      services:
        - name: mosquitto
          port: 1883
