apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mosquitto

resources:
  - ./namespace.yaml
  - ./config.yaml
  - ./volume.yaml
  - ./statefulset.yaml
  - ./service.yaml
  - ./ingress.yaml
