apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: tinyauth
  namespace: tinyauth
spec:
  entryPoints:
    - int-web-secure
  routes:
    - kind: Rule
      match: Host(`forward-auth.internal.ticklethepanda.co.uk`)
      services:
        - name: tinyauth
          port: 3000
