apiVersion: v1
kind: Service
metadata:
  labels:
    app: lldap-service
  name: lldap-service
spec:
  ports:
    - name: ldap
      port: 3890
      targetPort: 3890
    - name: web
      port: 80
      targetPort: 17170
  selector:
    app: lldap
