apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: odinbot

namePrefix: odinbot-
commonLabels:
  app: odinbot

resources:
  - ./deployment.yaml
  - ./service.yaml
  - ./volume.yaml
  - ./volume-claim.yaml
  - ./ingress.yaml
