apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: odin-counter

namePrefix: odin-counter-
commonLabels:
  app: odin-counter

resources:
  - ./deployment.yaml
  - ./service.yaml
  - ./volume.yaml
  - ./volume-claim.yaml
  - ./ingress.yaml
