apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: pocket-id
  namespace: pocket-id
spec:
  entryPoints:
    - auth-web-secure
  tls: {}
  routes:
    - kind: Rule
      match: Host(`auth.internal.ticklethepanda.co.uk`)
      services:
        - name: pocket-id
          port: 80
