apiVersion: apps/v1
kind: Deployment
metadata:
  name: octant
  namespace: octant
  labels:
    app: octant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: octant
  template:
    metadata:
      labels:
        app: octant
    spec:
      serviceAccountName: octant
      containers:
        - name: octant
          image: vmware-tanzu/octant:0.25.1
          args:
            - --disable-open-browser
            - --listener-addr=0.0.0.0:8000
          ports:
            - containerPort: 8000
