apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: octant
  namespace: octant
spec:
  entryPoints:
    - int-web
  routes:
    - kind: Rule
      match: Host(`octant.internal.ticklethepanda.co.uk`)
      services:
        - name: octant
          port: 80
