apiVersion: v1
kind: Service
metadata:
  name: octant
  namespace: octant
  annotations:
    metallb.io/address-pool: dashboard
spec:
  selector:
    app: octant
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
