apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
- ./setup
- ./home
- ./pihole
- ./cloudflared
- ./lldap

labels:
- includeSelectors: true
  pairs:
    ticklethepanda.dev/managed-by: kustomize
