apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: internal-ticklethepanda-co-uk
  namespace: kube-system
spec:
  dnsNames:
    - "*.internal.ticklethepanda.co.uk"
    - "internal.ticklethepanda.co.uk"
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt
  secretName: internal-ticklethepanda-co-uk
