apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ingress
spec:
  entryPoints:
    - int-web
  routes:
    - kind: Rule
      match: Host(`internal.ticklethepanda.co.uk`)
      middlewares:
        - name: auth
          namespace: home
      services:
        - name: internal-index-service
          namespace: home
          port: 80
    - kind: Rule
      match: Host(`internal.ticklethepanda.co.uk`) && Path(`/main.css`)
      services:
        - name: internal-index-service
          namespace: home
          port: 80
