apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: internal-index

namePrefix: internal-index-
commonLabels:
  app: internal-index

resources:
  - ./deployment.yaml
  - ./service.yaml
  - ./ingress.yaml
