---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  namespace: pihole
  labels:
    app: pihole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
        name: pihole
    spec:
      containers:
        - name: pihole
          image: pihole/pihole:2025.11.1
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: "Europe/London"
            - name: FTLCONF_webserver_api_password
              value: ""
            - name: SERVER_ADDR
              value: "pihole.internal.ticklethepanda.co.uk"
            - name: FTLCONF_LOCAL_IPV4
              value: "192.168.1.10"
            - name: VIRTUAL_HOST
              value: "pi.hole"
          volumeMounts:
            - name: pihole-etc-pv
              mountPath: "/etc/pihole"
            - name: pihole-dns-pv
              mountPath: "/etc/dnsmasq.d"
        - name: unbound
          image: mvance/unbound-rpi:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5335
              name: dns-udp
              protocol: UDP
            - containerPort: 5335
              name: dns-tcp
              protocol: TCP
          volumeMounts:
            - name: unbound-config
              mountPath: /opt/unbound/etc/unbound/unbound.conf
              subPath: unbound.conf
              readOnly: true
      volumes:
        - name: pihole-etc-pv
          persistentVolumeClaim:
            claimName: pihole-etc
        - name: pihole-dns-pv
          persistentVolumeClaim:
            claimName: pihole-dns
        - name: unbound-config
          configMap:
            name: unbound-config
