apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: pihole-ingress
  namespace: pihole
spec:
  entryPoints:
    - int-web-secure
  tls: {}
  routes:
    - kind: Rule
      match: Host(`pi-hole.internal.ticklethepanda.co.uk`)
      services:
        - name: pihole-web
          port: 80
