apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: pihole-ingress
  namespace: pihole
spec:
  entryPoints:
    - int-web-secure
  tls: {}
  routes:
    - kind: Rule
      match: Host(`pi-hole.internal.ticklethepanda.co.uk`)
      middlewares:
        - name: redirect-to-admin
        - name: tinyauth
          namespace: tinyauth
      services:
        - name: pihole-web
          port: 80

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirect-to-admin
  namespace: pihole
spec:
  redirectRegex:
    regex: "^https?://([^/]+)/?$"
    replacement: "https://${1}/admin/"
    permanent: false
