apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pihole

resources:
  - ./namespace.yaml
  - ./volume-conf.yaml
  - ./volume-dns.yaml
  - ./statefulset.yaml
  - ./service-lb.yaml
  - ./unbound-config.yaml
